name: Generate Metrics

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: header, repositories, activity, community, coding, commits
          plugin_traffic: yes
          plugin_languages: yes
          plugin_topics: yes
          plugin_streak: yes

      - name: Upload Metrics Image
        uses: actions/upload-artifact@v3
        with:
          name: metrics
          path: metrics.svg
